### ISSUE TITLE
Edit bond function does not allow bond's name to be changed

### ISSUE THREAD

**Issue by mong-nus** [AY1920S1-CS2113T-W17-3/main#100]
Based on the user guide, edit bond function allows user to edit bond's name. However, an error was thrown when user tries to edit the bond's name.

![image](https://user-images.githubusercontent.com/54018689/67110629-c677a980-f205-11e9-829a-fd6202e4ea58.png)

**Comment by shamussy** [comment]
@mong-nus this is not a bug per se, @BrianTKM  and I agreed that we should only allow users to change the interest rate (/rate) and year(/year). The year can only be changed towards a higher number.

**Comment by mong-nus** [comment]
Noted. Thanks for the clarification.

If that the case then we will have to amend the edit bond function in the user guide, as it state that user can change the bond name with /newname parameter.

**Comment by shamussy** [comment]
Yes noted, I will fix this along with issue #97
