### ISSUE TITLE
Credit card rebate does not have any cap

### ISSUE THREAD

**Issue by TerenceTanWT** [AY1920S1-CS2113T-W17-3/main#150]
Credit card rebate currently does not have any cap, which means user can set it to ridiculous amount. Implement check to ensure rebate does not exceed 0.2 (20%) and update regex from percentage to decimal.
Also to consider changing from decimal (0.2) to percentage (20%).

**Comment by shamussy** [comment]
> Credit card rebate currently does not have any cap, which means user can set it to ridiculous amount. Implement check to ensure rebate does not exceed 0.2 (20%) and update regex from percentage to decimal.
> Also to consider changing from decimal (0.2) to percentage (20%).

Would be better to keep it as whole numbers and convert it to percentage behind the scenes
