### ISSUE TITLE
Developer guide: use case did not specify which bank account to choose 

### ISSUE THREAD

**Issue by mong-nus** [AY1920S1-CS2113T-W17-3/main#156]
The use case should include information of which bank account to choose from. Below image is an example of the issue. 

![image](https://user-images.githubusercontent.com/54018689/67866344-c5c70780-fb63-11e9-823a-e2561952062f.png)

**Comment by valerietyj** [comment]
Requires minor change to UC 5 to properly cover editing of bank accounts
