### ISSUE TITLE
Developer Guide: 3.3.1 Parser Class Diagram missing ParseCardBill

### ISSUE THREAD

**Issue by TerenceTanWT** [AY1920S1-CS2113T-W17-3/main#171]
![image](https://user-images.githubusercontent.com/9088116/67948923-ab536380-fc21-11e9-85c9-5b83417b859a.png)

The General Parser Class Diagram (figure 4) in section 3.3.1 Parser of the DG is missing the ParseCardBill abstract class. Please add it in the diagram and update the comments.

**Comment by shamussy** [comment]
Resolved in #228
