### ISSUE TITLE
Program behaviour: The error message is confusing

### ISSUE THREAD

**Issue by Dou-Maokang** [AY1920S1-CS2113T-W17-3/main#180]
<img width="975" alt="image" src="https://user-images.githubusercontent.com/54148939/68015571-64bb4300-fccd-11e9-84ff-de70841e9a42.png">

My Account 001 should be the sender account, thus the sender account does exist while the receiver account does not exist.

**Comment by shamussy** [comment]
Hi there You entered 2 spacebars 
![image](https://user-images.githubusercontent.com/35601296/68016108-c62fe180-fcce-11e9-8db2-dd50813d9d03.png)
