### ISSUE TITLE
Extra category in deposit?

### ISSUE THREAD

**Issue by shamussy** [AY1920S1-CS2113T-W17-3/main#212]
![image](https://user-images.githubusercontent.com/35601296/68392962-e9163600-01a5-11ea-99e9-c81d342c5652.png)

![image](https://user-images.githubusercontent.com/35601296/68392971-efa4ad80-01a5-11ea-960c-f291c02322f9.png)

I think this should not be happening right? Is the /category necessary in the deposit keywords? Even if the user inputs, it is overwritten as deposit if i remember correctly?

**Comment by BrianTKM** [comment]
/category is not used here. Thanks for finding out about this

**Comment by shamussy** [comment]
Fixed in #210
