### ISSUE TITLE
Extra /date in recurringbankexp

### ISSUE THREAD

**Issue by shamussy** [AY1920S1-CS2113T-W17-3/main#213]
![image](https://user-images.githubusercontent.com/35601296/68393648-6a21fd00-01a7-11ea-8ca3-486ae068b313.png)

is /date supposed to be used in recurbankexp?

**Comment by BrianTKM** [comment]
/date is not used here. Thanks for finding out about this

**Comment by shamussy** [comment]
> /date is not used here. Thanks for finding out about this

![image](https://user-images.githubusercontent.com/35601296/68395710-406ad500-01ab-11ea-8fab-04f77597df7a.png)

![image](https://user-images.githubusercontent.com/35601296/68395728-482a7980-01ab-11ea-97a5-622486e5e791.png)


are their usages supposed to be removed as well?

**Comment by BrianTKM** [comment]
yes there should not be any issues with removing all instances of the date parameters in recurring expenditures. Same for all ParseDeposit for issue #212 for /category

**Comment by shamussy** [comment]
Fixed in #210
