### ISSUE TITLE
Overflow of integer possibility

### ISSUE THREAD

**Issue by shamussy** [AY1920S1-CS2113T-W17-3/main#99]
- [x] We have not accounted for situations where there are too many transactions in the transaction list, card list, bank list etc.
- [ ] We should also limit the number of bank accounts, cards to allow users to add as well. But a minimum of 1 savings account must be present
- [x] We have also not accounted for situations where the bank account is currently at its maximum limit and the interest rates come in.

**Comment by shamussy** [comment]
Checking third option, so far based on testing, it is impossible to overflow the double limit with a max of 20 bonds at all max amount of money and max interest rate.

**Comment by BrianTKM** [comment]
We have not accounted for situations where there are too many transactions in the transaction list, card list, bank list etc. Resolved in PR #107

**Comment by BrianTKM** [comment]
@TerenceTanWT the number of bank accounts have been limited already. Once you are done, can check that option
